### ISSUE TITLE
Don't work on gentoo

### ISSUE THREAD

**Issue by not-null-nil** [shvchk/poly-light#6]
I like this theme very much and tried it on my Gentoo.
But a problem occurred

```
Adding theme to GRUB config
GRUB_THEME=/boot/grub/themes/poly-light/theme.txt
Updating GRUB
sudo: update-grub: command not found
Removing theme installation files

``` 

I have tried 

`➜  nil grub-mkconfig -o `/boot/grub/grub.cfg`

and the output looks like that

`                             
Generating grub configuration file ...
Found theme: /boot/grub/themes/poly-light/theme.txt
done`

But it doesn't work, how should I fix this?

**Comment by gesangtome** [comment]
@MorosithIi 
The installation script does have such a problem. I may submit patches for Redhat and subversions to fix it, gentoo I haven't used it yet, so I don't know how to fix it.

**Comment by not-null-nil** [comment]
@Flowertome I have gave up, thank you anyway

**Comment by shvchk** [comment]
Installation script assumes GRUB uses themes from `/boot/grub/themes`, 'high-level' GRUB config is `/etc/default/grub` and `update-grub` rebuilds 'low-level' GRUB config, which might not be the case on Gentoo. I'll have a look soon, thanks for reporting and sorry for late reply :grimacing:

**Comment by shvchk** [comment]
Can't reproduce the problem. I've downloaded [VirtualBox image from osboxes.org](https://www.osboxes.org/gentoo/#gentoo-201703-vbox), launched theme install script, it worked fine except `sudo: update-grub: command not found` error, which was fixed with `sudo grub-mkconfig -o /boot/grub/grub.cfg`. I'm not very familiar with Gentoo (actually it was the first time I tried it :wink: ), but might it be that you have GRUB built without themes support?

I will probably add OS detection to the install script, though, so it uses the right command to update GRUB config (`update-grub` is Debian and derivatives specific, it seems).

UPD: You might try to ask for help in [Telemin/gentoo-grub-themes](https://github.com/Telemin/gentoo-grub-themes) (this repo is specifically focused on Gentoo GRUB themes) or [Gentoo IRC channel](https://gentoo.org/get-involved/irc-channels/) (also available in [other languages](https://gentoo.org/get-involved/irc-channels/all-channels.html))

**Comment by not-null-nil** [comment]
@shvchk I have rebuilt grub2 with tags "fonts" and "themes", but it still don't work. I will go to IRC, thanks to your advice.

**Comment by shvchk** [comment]
Added distro detection to use distro-specific GRUB location and update method in 64feeb7

Closing this for now, as this issue doesn't seem to be caused by this theme, but feel free to reopen if it is or comment when you figure out what the problem was and how to fix it :wink:

**Comment by shvchk** [comment]
@MorosithIi You might also want to look into `/etc/grub.d/` — scripts there could override theme settings. I'd search for keywords like "theme", "background" and "color", then try to temporary move suspicious files from this folder. See [similar problem](https://www.reddit.com/r/linuxquestions/comments/81y0h9/grub2_customization_theming_not_working/dve1f9f/).

**Comment by not-null-nil** [comment]
@shvchk I have jus reinstalled Gentoo, and this time it worked beautifully. Thanks for your work very much.
By the way, I just wondering is there a dark one and to my surprise, there was really one. I am going to try it tomorrow, thanks again.
By the way of the way (don't care it, please ) , can you share how to make the background, I really want to try a different color to suit my lock scren and desktop background. Thanks again again.

**Comment by shvchk** [comment]
Glad to know it works for you! To make theme use your background image, put it into theme directory, and change setting in `theme.txt` from `desktop-image: "background.png"` to `desktop-image: "your-image-name.png-or-jpg"`. You can learn more on customization here: http://wiki.rosalab.ru/en/index.php/Grub2_theme_tutorial

**Comment by not-null-nil** [comment]
@shvchk Thanks for your reply! And do will you mind if I change the colour of the background picture you provided? If don't, can you please tell me how to do it?

**Comment by shvchk** [comment]
Yeah, do what you like :wink: 
To change color, you can use GIMP, first change image to RGB (menu Image → Mode → RGB), then use one or combination of these filters:
- [Colors → Hue-Saturation](https://docs.gimp.org/en/gimp-tool-hue-saturation.html)
- [Colors → Colorize](https://docs.gimp.org/en/gimp-tool-colorize.html)
- [Colors → Colorify](https://docs.gimp.org/en/plug-in-colorify.html)
- [Colors → Invert](https://docs.gimp.org/en/gimp-layer-invert.html)

**Comment by not-null-nil** [comment]
@shvchk Thank you very much.
